import { defineArchitecture } from "./scripts/architecture/define-architecture.js";

export const architecture = defineArchitecture({
  apps: {
    sandbox: {
      dependencies: [
        "sandbox-runtime",
        "configuration",
        "sandbox-images",
        "sandbox-resources",
        "sandbox-containers",
        "host-command-escape",
        "network",
        "network-diagnostics",
        "sandbox-settings",
        "storage",
        "workspace-setup",
        "assistance",
        "diagnostics",
        "self-update",
        "container-runtime",
        "clock",
        "process",
        "dependency-injection",
        "environment",
        "filesystem",
        "logging",
        "terminal",
        "websocket",
        "errors",
        "text",
      ],
    },
    "sandbox-container-tools": {
      dependencies: [
        "network",
        "sandbox-settings",
        "container-system",
        "clock",
        "dependency-injection",
        "environment",
        "process",
        "logging",
        "terminal",
      ],
    },
  },
  modules: {
    configuration: {
      dependencies: [
        "host-command-escape",
        "container-runtime",
        "filesystem",
        "environment",
        "clock",
        "git",
        "dependency-injection",
        "logging",
        "terminal",
        "text",
      ],
    },
    "host-command-escape": {
      dependencies: [
        "websocket",
        "process",
        "environment",
        "filesystem",
        "logging",
        "terminal",
      ],
      testDependencies: ["dependency-injection"],
    },
    "sandbox-images": {
      assets: ["docker"],
      dependencies: [
        "configuration",
        "sandbox-resources",
        "container-runtime",
        "state",
        "filesystem",
        "environment",
        "logging",
        "terminal",
        "text",
      ],
    },
    "sandbox-runtime": {
      dependencies: [
        "storage",
        "clock",
        "container-runtime",
        "environment",
        "filesystem",
        "logging",
      ],
    },
    "sandbox-containers": {
      dependencies: [
        "sandbox-runtime",
        "configuration",
        "sandbox-images",
        "sandbox-resources",
        "host-command-escape",
        "network",
        "sandbox-settings",
        "storage",
        "container-runtime",
        "state",
        "clock",
        "filesystem",
        "environment",
        "git",
        "logging",
        "terminal",
        "text",
      ],
      testDependencies: ["dependency-injection"],
    },
    network: {
      dependencies: ["configuration", "container-system"],
    },
    "network-diagnostics": {
      dependencies: [
        "configuration",
        "network",
        "container-runtime",
        "container-system",
        "clock",
        "filesystem",
        "logging",
        "terminal",
        "text",
        "time",
      ],
    },
    "sandbox-resources": {
      dependencies: ["container-runtime", "state"],
    },
    "sandbox-settings": {
      dependencies: [
        "configuration",
        "storage",
        "filesystem",
        "environment",
        "logging",
        "terminal",
      ],
    },
    storage: {
      dependencies: [
        "configuration",
        "filesystem",
        "environment",
        "logging",
        "text",
      ],
    },
    "workspace-setup": {
      assets: ["templates"],
      dependencies: [
        "configuration",
        "sandbox-resources",
        "sandbox-settings",
        "state",
        "filesystem",
        "environment",
        "git",
        "terminal",
        "errors",
      ],
    },
    assistance: {
      dependencies: [
        "sandbox-runtime",
        "configuration",
        "sandbox-images",
        "sandbox-settings",
        "workspace-setup",
        "filesystem",
        "environment",
        "git",
        "logging",
        "terminal",
        "text",
      ],
    },
    diagnostics: {
      dependencies: [
        "configuration",
        "sandbox-settings",
        "container-runtime",
        "clock",
        "filesystem",
        "environment",
        "terminal",
      ],
    },
    "self-update": {
      dependencies: [
        "workspace-setup",
        "npm",
        "process",
        "environment",
        "state",
        "filesystem",
        "clock",
        "logging",
        "terminal",
        "errors",
      ],
      testDependencies: ["dependency-injection"],
    },
  },
  platform: {
    "container-runtime": {
      dependencies: [
        "process",
        "clock",
        "environment",
        "filesystem",
        "logging",
        "terminal",
        "dependency-injection",
        "text",
      ],
    },
    process: {
      dependencies: ["clock", "dependency-injection", "logging", "text"],
    },
    websocket: { dependencies: ["dependency-injection"] },
    clock: { dependencies: ["dependency-injection"] },
    filesystem: { dependencies: ["environment"] },
    environment: {
      dependencies: ["process", "logging", "dependency-injection"],
    },
    git: { dependencies: ["process", "filesystem", "text"] },
    logging: { dependencies: ["clock", "dependency-injection"] },
    terminal: {
      dependencies: ["dependency-injection", "environment", "process"],
    },
    "dependency-injection": { dependencies: [] },
    npm: { dependencies: ["process", "clock"] },
    state: { dependencies: ["filesystem", "environment"] },
    "container-system": {
      dependencies: [
        "clock",
        "filesystem",
        "environment",
        "process",
        "logging",
        "terminal",
        "dependency-injection",
      ],
    },
  },
  shared: {
    errors: { dependencies: [] },
    text: { dependencies: [] },
    time: { dependencies: [] },
  },
  testApis: [
    "apps/sandbox-container-tools",
    "modules/configuration",
    "modules/network-diagnostics",
    "modules/self-update",
    "platform/clock",
    "platform/container-runtime",
    "platform/container-system",
    "platform/environment",
    "platform/process",
    "platform/git",
    "platform/npm",
    "platform/terminal",
  ],
  legacyRoots: [],
});
