import * as path from "node:path";
import { shellQuote } from "#shared/text/index.js";
import type { ImageSetupAction } from "./image-setup.js";
import type { ToolDefinition } from "./tool-definition.js";

interface GeneratorOptions {
  tools: ToolDefinition[];
  baseImage: string;
  includeComments?: boolean;
  toolIds?: string[];
}

interface ImageSetupPhases {
  root: ImageSetupAction[];
  containerUser: ImageSetupAction[];
}

type PackageActionKind = Extract<
  ImageSetupAction["kind"],
  | "install-apt-packages"
  | "install-npm-packages"
  | "install-mise-tools"
  | "install-go-packages"
  | "install-cargo-packages"
>;

function isPackageActionKind(
  kind: ImageSetupAction["kind"],
): kind is PackageActionKind {
  return (
    kind === "install-apt-packages" ||
    kind === "install-npm-packages" ||
    kind === "install-mise-tools" ||
    kind === "install-go-packages" ||
    kind === "install-cargo-packages"
  );
}

function bundledOwnedPaths(
  actions: readonly ImageSetupAction[],
  kind: PackageActionKind,
): string[] {
  return actions
    .filter((action) => action.kind === kind)
    .flatMap((action) => action.chownToContainerUser);
}

function bundlePackageAction(
  actions: readonly ImageSetupAction[],
  kind: PackageActionKind,
): ImageSetupAction {
  const ownedPaths = bundledOwnedPaths(actions, kind);
  switch (kind) {
    case "install-apt-packages":
      return {
        kind,
        packages: actions.flatMap((action) =>
          action.kind === kind ? action.packages : [],
        ),
        chownToContainerUser: ownedPaths,
      };
    case "install-npm-packages":
      return {
        kind,
        packages: actions.flatMap((action) =>
          action.kind === kind ? action.packages : [],
        ),
        chownToContainerUser: ownedPaths,
      };
    case "install-mise-tools":
      return {
        kind,
        tools: actions.flatMap((action) =>
          action.kind === kind ? action.tools : [],
        ),
        chownToContainerUser: ownedPaths,
      };
    case "install-go-packages":
      return {
        kind,
        packages: actions.flatMap((action) =>
          action.kind === kind ? action.packages : [],
        ),
        chownToContainerUser: ownedPaths,
      };
    case "install-cargo-packages":
      return {
        kind,
        packages: actions.flatMap((action) =>
          action.kind === kind ? action.packages : [],
        ),
        chownToContainerUser: ownedPaths,
      };
  }
}

function bundlePackageActions(
  actions: readonly ImageSetupAction[],
): ImageSetupAction[] {
  const emitted = new Set<PackageActionKind>();
  const result: ImageSetupAction[] = [];
  for (const action of actions) {
    if (!isPackageActionKind(action.kind)) {
      result.push(action);
      continue;
    }
    if (emitted.has(action.kind)) continue;
    emitted.add(action.kind);
    result.push(bundlePackageAction(actions, action.kind));
  }
  return result;
}

function collectImageSetup(tools: readonly ToolDefinition[]): ImageSetupPhases {
  return {
    root: bundlePackageActions(
      tools.flatMap((tool) => tool.imageSetup?.asRoot ?? []),
    ),
    containerUser: bundlePackageActions(
      tools.flatMap((tool) => tool.imageSetup?.asContainerUser ?? []),
    ),
  };
}

function addHeader(lines: string[], options: GeneratorOptions): void {
  if (options.includeComments) {
    lines.push("# Generated by: sandbox init");
    if (options.toolIds) {
      lines.push(`# Tools: ${options.toolIds.join(",")}`);
    }
    lines.push("# Mise registry: https://mise.jdx.dev/registry.html");
  }
  lines.push(`FROM ${options.baseImage}`, "");
}

function formatPackageRun(
  command: string,
  packages: readonly string[],
): string {
  if (packages.length <= 1) return `RUN ${command} ${packages.join("")}`;
  return `RUN ${command} \\\n${packages.map((entry) => `      ${entry}`).join(" \\\n")}`;
}

function formatMiseRun(tools: readonly string[]): string {
  const command = formatPackageRun("mise use -g", tools);
  return command.replace(
    "RUN ",
    "RUN --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN ",
  );
}

function generateAction(action: ImageSetupAction): string[] {
  switch (action.kind) {
    case "install-apt-packages":
      return [
        "RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\",
        "    --mount=type=cache,target=/var/lib/apt,sharing=locked \\",
        `    apt-get update && apt-get install -y --no-install-recommends ${action.packages.join(" ")}`,
      ];
    case "install-npm-packages":
      return [formatPackageRun("npm install -g", action.packages)];
    case "install-mise-tools":
      return [formatMiseRun(action.tools)];
    case "install-go-packages":
      return [formatPackageRun("go install", action.packages)];
    case "install-cargo-packages":
      return [
        `RUN ${action.packages.map((entry) => `cargo install ${entry}`).join(" && ")}`,
      ];
    case "run-commands":
      return action.commands.length === 0
        ? []
        : [`RUN ${action.commands.join(" && ")}`];
    case "add-dockerfile-lines":
      return [...action.lines];
    case "add-path-entries":
      return [
        `ENV PATH="${[...action.prepend, "$PATH", ...action.append].join(":")}"`,
      ];
    case "add-shell-setup":
      return action.lines.length === 0
        ? []
        : [
            `${formatPackageRun("printf '%s\\n'", action.lines.map(shellQuote))} >> ~/.profile`,
          ];
  }
}

function validateAndCollectOwnedPaths(
  rootActions: readonly ImageSetupAction[],
): string[] {
  const ownedPaths = new Set<string>();
  for (const action of rootActions) {
    for (const ownedPath of action.chownToContainerUser) {
      if (!path.posix.isAbsolute(ownedPath)) {
        throw new Error(
          `Image setup owned path must be an absolute container path: ${ownedPath}`,
        );
      }
      ownedPaths.add(ownedPath);
    }
  }
  return [...ownedPaths];
}

function addActions(
  lines: string[],
  actions: readonly ImageSetupAction[],
): void {
  for (const action of actions) {
    const generated = generateAction(action);
    if (generated.length === 0) continue;
    lines.push(...generated, "");
  }
}

export function generateDockerfile(options: GeneratorOptions): string {
  const normalizedOptions = {
    ...options,
    includeComments: options.includeComments ?? true,
  };
  const phases = collectImageSetup(options.tools);
  const ownedPaths = validateAndCollectOwnedPaths(phases.root);
  const allActions = [...phases.root, ...phases.containerUser];
  const hasMiseTools = allActions.some(
    (action) => action.kind === "install-mise-tools",
  );
  const lines: string[] = [];

  addHeader(lines, normalizedOptions);

  if (normalizedOptions.includeComments && allActions.length > 0) {
    lines.push("# Languages and tools", "");
  }

  if (phases.root.length > 0) {
    lines.push("USER root", "");
    addActions(lines, phases.root);
  }

  if (ownedPaths.length > 0) {
    lines.push(`RUN chown -R sandbox:sandbox ${ownedPaths.join(" ")}`, "");
  }

  lines.push("USER sandbox", "");
  if (hasMiseTools && normalizedOptions.includeComments) {
    lines.push(
      "# GITHUB_TOKEN is available as an optional build secret for API rate limits",
      "# https://github.com/settings/tokens (no scopes needed for public repos)",
      "",
    );
  }
  addActions(lines, phases.containerUser);

  lines.push(
    "# Runtime entrypoint starts as root and drops privileges for sessions",
    "USER root",
    "",
  );

  return lines.join("\n");
}
