import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import * as fs from "node:fs";
import * as path from "node:path";
import { cleanupTestDir, createTestDir } from "#test/utils.js";
import { defineCategory } from "../tools/category-definition.js";
import type { ToolDefinition } from "../tools/tool-definition.js";
import { resolveTools } from "../tools/tool-resolution.js";
import {
  parseToolIdsFromDockerfile,
  readToolIdsFromDockerfile,
  validateToolIds,
} from "./build-context-detection.js";

describe("parseToolIdsFromDockerfile", () => {
  test("parses tool IDs from header comment", () => {
    const content = [
      "# Generated by: sandbox init",
      "# Tools: claude,node,bun",
      "# Mise registry: https://mise.jdx.dev/registry.html",
      "FROM sandbox-base:latest",
    ].join("\n");

    expect(parseToolIdsFromDockerfile(content)).toEqual([
      "claude",
      "node",
      "bun",
    ]);
  });

  test("restores each legacy metadata entry as a direct selection", () => {
    const directIds = parseToolIdsFromDockerfile(
      "# Tools: agent-browser,node\nFROM base",
    );
    const result = resolveTools(directIds ?? []);

    expect(result.directSelections.map((tool) => tool.id)).toEqual([
      "agent-browser",
      "node",
    ]);
    expect(result.automaticSelections.map((tool) => tool.id)).toEqual([
      "chromium",
    ]);
  });

  test("handles spaces around commas", () => {
    const content = "# Tools: claude , node , bun\nFROM base";
    expect(parseToolIdsFromDockerfile(content)).toEqual([
      "claude",
      "node",
      "bun",
    ]);
  });

  test("handles single tool", () => {
    const content = "# Tools: node\nFROM base";
    expect(parseToolIdsFromDockerfile(content)).toEqual(["node"]);
  });

  test("restores an empty direct selection", () => {
    expect(parseToolIdsFromDockerfile("# Tools:\nFROM base")).toEqual([]);
  });

  test("returns null when comment is missing", () => {
    const content = [
      "# Generated by: sandbox init",
      "FROM sandbox-base:latest",
    ].join("\n");

    expect(parseToolIdsFromDockerfile(content)).toBeNull();
  });

  test("returns null for empty content", () => {
    expect(parseToolIdsFromDockerfile("")).toBeNull();
  });

  test("filters out empty strings from trailing commas", () => {
    const content = "# Tools: node,bun,\nFROM base";
    expect(parseToolIdsFromDockerfile(content)).toEqual(["node", "bun"]);
  });
});

describe("readToolIdsFromDockerfile", () => {
  let testDir: string;

  beforeEach(() => {
    testDir = createTestDir("dockerfile-parser");
  });

  afterEach(() => {
    cleanupTestDir(testDir);
  });

  test("returns null when file does not exist", () => {
    const result = readToolIdsFromDockerfile(path.join(testDir, "nonexistent"));
    expect(result).toBeNull();
  });

  test("returns null when file has no Tools comment", () => {
    const filePath = path.join(testDir, "Dockerfile");
    fs.writeFileSync(filePath, "FROM base:latest\nRUN echo hello");
    expect(readToolIdsFromDockerfile(filePath)).toBeNull();
  });

  test("returns parsed tool IDs when comment exists", () => {
    const filePath = path.join(testDir, "Dockerfile");
    fs.writeFileSync(filePath, "# Tools: node,bun,claude\nFROM base:latest");
    expect(readToolIdsFromDockerfile(filePath)).toEqual([
      "node",
      "bun",
      "claude",
    ]);
  });

  test("returns single tool ID", () => {
    const filePath = path.join(testDir, "Dockerfile");
    fs.writeFileSync(filePath, "# Tools: node\nFROM base:latest");
    expect(readToolIdsFromDockerfile(filePath)).toEqual(["node"]);
  });
});

describe("validateToolIds", () => {
  const testCategory = defineCategory({
    id: "test",
    name: "Test",
    section: "languages",
    description: "Test runtimes",
  });
  const testRegistry: ToolDefinition[] = [
    {
      id: "node",
      name: "Node.js",
      description: "JS runtime",
      category: testCategory,
    },
    {
      id: "bun",
      name: "Bun",
      description: "Fast JS runtime",
      category: testCategory,
    },
  ];

  test("all valid IDs", () => {
    const result = validateToolIds(["node", "bun"], testRegistry);
    expect(result.valid).toEqual(["node", "bun"]);
    expect(result.unknown).toEqual([]);
  });

  test("some unknown IDs", () => {
    const result = validateToolIds(
      ["node", "removed-tool", "bun"],
      testRegistry,
    );
    expect(result.valid).toEqual(["node", "bun"]);
    expect(result.unknown).toEqual(["removed-tool"]);
  });

  test("all unknown IDs", () => {
    const result = validateToolIds(["foo", "bar"], testRegistry);
    expect(result.valid).toEqual([]);
    expect(result.unknown).toEqual(["foo", "bar"]);
  });

  test("empty input", () => {
    const result = validateToolIds([], testRegistry);
    expect(result.valid).toEqual([]);
    expect(result.unknown).toEqual([]);
  });
});
