import { describe, expect, test } from "bun:test";
import { setupSandboxAppTest } from "./__test__/sandbox-app-test.js";

type App = Awaited<ReturnType<typeof setupSandboxAppTest>>;

async function confirmInitialAgents(app: App): Promise<void> {
  await app.tui.waitForText("Select AI agents first");
  await app.tui.user.enter();
}

async function reviewCapabilities(app: App): Promise<void> {
  await app.tui.waitForText("Configure capabilities");
  await app.tui.user.type("G");
  await app.tui.user.enter();
  await app.tui.waitForText("Review capabilities");
  await app.tui.user.enter();
}

async function openDiffActions(app: App, fileName: string): Promise<void> {
  await app.tui.waitForText(`Do you want to update ${fileName}?`);
}

async function reviewUserCapabilities(app: App): Promise<void> {
  await confirmInitialAgents(app);
  await reviewCapabilities(app);
}

async function customizeProjectImage(app: App): Promise<void> {
  await app.tui.waitForText("Customize the project image?");
  await app.tui.user.type("y");
}

async function reviewProjectCapabilities(app: App): Promise<void> {
  await customizeProjectImage(app);
  await reviewCapabilities(app);
}

async function selectCapability(app: App, query: string): Promise<void> {
  await app.tui.waitForText("Configure capabilities");
  await app.tui.user.type(`/${query}`);
  await app.tui.waitForText(query);
  await app.tui.user.enter();
  await app.tui.user.down(2);
  await app.tui.user.space();
  await app.tui.user.type("G");
  await app.tui.user.enter();
  await app.tui.waitForText("Review capabilities");
  await app.tui.user.enter();
}

function resetNonGitProject(app: App): void {
  app.workspace.git.givenNoRepository(app.project.root);
}

describe("sandbox init", () => {
  test("creates user files and remains isolated from process workspace values", async () => {
    await using app = await setupSandboxAppTest();

    const execution = app.cli.run("init");
    await app.tui.waitForText("Select AI agents first");
    expect(app.tui.screen()).not.toContain("Configure capabilities");
    await app.tui.user.enter();
    await reviewCapabilities(app);
    const result = await execution;

    expect(result).toMatchObject({ exitCode: 0, stderr: "" });
    expect(result.stdout).toContain("Welcome to Sandbox");
    expect(result.stdout).toContain("Environment");
    expect(app.workspace.configFileExists("config.toml")).toBe(true);
    expect(app.workspace.configFileExists("docker/Dockerfile")).toBe(true);
    expect(app.workspace.configFileExists("settings/.gitignore")).toBe(true);
    expect(app.workspace.configFileExists("state.json")).toBe(false);
    const dockerfile = app.workspace.readConfigFile("docker/Dockerfile");
    expect(dockerfile).toContain("FROM sandbox-base:latest");
    expect(dockerfile).toContain("# Tools: node,bun,pnpm,python,uv");
    expect(dockerfile).toContain("python@3.13");
  });

  test("copies detected agent settings and enables the selected bypass", async () => {
    await using app = await setupSandboxAppTest();
    app.workspace.writeHomeFile(
      ".claude/settings.json",
      '{"existingSetting":true}',
    );

    const execution = app.cli.run("init");
    await app.tui.waitForText("Select AI agents first");
    await app.tui.user.space();
    await app.tui.user.enter();
    await reviewCapabilities(app);
    await app.tui.waitForText("Select configurations to copy or create");
    await app.tui.user.enter();
    await app.tui.waitForText("Skip agent permission prompts");
    await app.tui.user.enter();

    const result = await execution;
    expect(result).toMatchObject({ exitCode: 0, stderr: "" });
    expect(result.stdout.indexOf("Configure capabilities")).toBeLessThan(
      result.stdout.indexOf("Agent configurations"),
    );
    const copied = JSON.parse(
      app.workspace.readConfigFile("settings/.claude/settings.json"),
    );
    expect(copied).toMatchObject({
      existingSetting: true,
      permissions: { defaultMode: "bypassPermissions" },
    });
  });

  test("adds detected user capabilities without removing broad defaults", async () => {
    await using app = await setupSandboxAppTest();
    app.workspace.writeExecutable("java");

    const execution = app.cli.run("init");
    await reviewUserCapabilities(app);
    expect(await execution).toMatchObject({ exitCode: 0, stderr: "" });

    expect(app.workspace.readConfigFile("docker/Dockerfile")).toContain(
      "# Tools: node,bun,pnpm,python,uv,java",
    );
  });

  test("restores generated direct selections and includes automatic dependencies", async () => {
    await using app = await setupSandboxAppTest();
    app.global.writeDockerfile(
      "# Generated by: sandbox init\n# Tools: copilot\nFROM sandbox-base:latest\n",
    );

    const execution = app.cli.run("init");
    await confirmInitialAgents(app);
    await reviewCapabilities(app);
    await openDiffActions(app, "docker/Dockerfile");
    await app.tui.user.enter();
    expect(await execution).toMatchObject({ exitCode: 0, stderr: "" });

    const dockerfile = app.workspace.readConfigFile("docker/Dockerfile");
    expect(dockerfile).toContain("# Tools: copilot");
    expect(dockerfile).not.toContain("# Tools: node");
    expect(dockerfile).toContain("mise use -g node@lts");
    expect(dockerfile).toContain("npm install -g @github/copilot@latest");
  });

  test("restores an empty generated direct selection without applying defaults", async () => {
    await using app = await setupSandboxAppTest();
    app.global.writeDockerfile(
      "# Generated by: sandbox init\n# Tools:\nFROM sandbox-base:latest\n",
    );

    const execution = app.cli.run("init");
    await reviewUserCapabilities(app);
    await openDiffActions(app, "docker/Dockerfile");
    await app.tui.user.enter();
    expect(await execution).toMatchObject({ exitCode: 0, stderr: "" });

    const dockerfile = app.workspace.readConfigFile("docker/Dockerfile");
    expect(dockerfile).toContain("# Tools: \n");
    expect(dockerfile).not.toContain("mise use -g");
  });

  test("lets the user revise the initial agent selection in the complete tree", async () => {
    await using app = await setupSandboxAppTest();

    const execution = app.cli.run("init");
    await app.tui.waitForText("Select AI agents first");
    await app.tui.user.space();
    await app.tui.user.enter();
    await selectCapability(app, "code.claude.com");
    expect(await execution).toMatchObject({ exitCode: 0, stderr: "" });

    expect(app.workspace.readConfigFile("docker/Dockerfile")).not.toContain(
      "claude",
    );
    expect(
      app.workspace.configFileExists("settings/.claude/settings.json"),
    ).toBe(false);
  });

  test("cancels from the initial agent screen without creating user files", async () => {
    await using app = await setupSandboxAppTest();

    const execution = app.cli.run("init");
    await app.tui.waitForText("Select AI agents first");
    await app.tui.user.chord("c", { ctrl: true });
    const result = await execution;

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("Cancelled.");
    expect(app.workspace.configFileExists("config.toml")).toBe(false);
    expect(app.workspace.configFileExists("docker/Dockerfile")).toBe(false);
  });

  test("creates project files with explicit tools in a non-Git workspace", async () => {
    await using app = await setupSandboxAppTest();
    app.workspace.writeExecutable("claude");
    app.workspace.writeRootFile(
      "project/.mise.toml",
      "[tools]\nnode = 'lts'\n",
    );

    const result = await app.cli.run(
      "init",
      "--project",
      "--tools",
      "node,pnpm",
    );

    expect(result).toMatchObject({ exitCode: 0, stderr: "" });
    expect(result.stdout).toContain("Created");
    const dockerfile = app.workspace.readProjectFile(
      ".sandbox/docker/Dockerfile",
    );
    expect(dockerfile).toContain("# Tools: node,pnpm");
    expect(dockerfile).not.toContain("claude");
    expect(app.workspace.projectFileExists(".sandbox/docker/.mise.toml")).toBe(
      false,
    );
    expect(app.workspace.readProjectFile(".sandbox/config.toml")).toContain(
      "Project-specific sandbox config",
    );
    expect(app.workspace.git.operations()).not.toHaveLength(0);
  });

  test("creates only project config when image customization is declined", async () => {
    await using app = await setupSandboxAppTest();

    const execution = app.cli.run("init", "--project");
    await app.tui.waitForText("Customize the project image?");
    await app.tui.user.enter();

    expect(await execution).toMatchObject({ exitCode: 0, stderr: "" });
    expect(app.workspace.projectFileExists(".sandbox/config.toml")).toBe(true);
    expect(app.workspace.projectFileExists(".sandbox/docker/Dockerfile")).toBe(
      false,
    );
  });

  test("preserves an existing project Dockerfile when customization is declined", async () => {
    await using app = await setupSandboxAppTest();
    app.project.writeDockerfile("FROM custom-image\n");

    const execution = app.cli.run("init", "--project");
    await app.tui.waitForText("Customize the project image?");
    await app.tui.user.enter();

    expect(await execution).toMatchObject({ exitCode: 0, stderr: "" });
    expect(app.workspace.readProjectFile(".sandbox/docker/Dockerfile")).toBe(
      "FROM custom-image\n",
    );
  });

  test("rejects unknown capabilities in non-interactive project setup", async () => {
    await using app = await setupSandboxAppTest();

    const result = await app.cli.run(
      "init",
      "--project",
      "--tools",
      "unknown-capability",
    );

    expect(result.exitCode).toBe(1);
    expect(result.stderr).toContain("Unknown tool IDs: unknown-capability");
    expect(app.workspace.projectFileExists(".sandbox/config.toml")).toBe(false);
    expect(app.workspace.projectFileExists(".sandbox/docker/Dockerfile")).toBe(
      false,
    );
  });

  test("selects a project capability and reviews it", async () => {
    await using app = await setupSandboxAppTest();

    const execution = app.cli.run("init", "--project");
    await customizeProjectImage(app);
    await app.tui.waitForText("Node.js + npm");
    await app.tui.user.down(2);
    await app.tui.user.space();
    await app.tui.waitForText("● Node.js + npm");
    await app.tui.user.type("G");
    await app.tui.user.enter();
    await app.tui.waitForText("Review capabilities");
    await app.tui.user.enter();

    expect(await execution).toMatchObject({ exitCode: 0, stderr: "" });
    expect(
      app.workspace.readProjectFile(".sandbox/docker/Dockerfile"),
    ).toContain("# Tools: node");
  });

  test("detects lock files at the resolved project root without selecting agents", async () => {
    await using app = await setupSandboxAppTest();
    app.workspace.writeRootFile("package.json", "{}\n");
    app.workspace.writeRootFile("pnpm-lock.yaml", "lockfileVersion: '9.0'\n");
    app.workspace.writeExecutable("claude");
    app.workspace.git.givenRepository({
      root: app.workspace.root,
      queriedPath: app.project.root,
    });

    const execution = app.cli.run("init", "--project");
    await reviewProjectCapabilities(app);
    expect(await execution).toMatchObject({ exitCode: 0, stderr: "" });

    const dockerfile = app.workspace.readProjectFile(
      ".sandbox/docker/Dockerfile",
    );
    expect(dockerfile).toContain("# Tools: node,pnpm");
    expect(dockerfile).not.toContain("claude");
  });

  test("detects build context at the Git root and copies selected files", async () => {
    await using app = await setupSandboxAppTest();
    app.workspace.writeRootFile(".mise.toml", "[tools]\nnode = 'lts'\n");
    app.workspace.git.givenRepository({
      root: app.workspace.root,
      queriedPath: app.project.root,
    });

    const execution = app.cli.run("init", "--project");
    await reviewProjectCapabilities(app);
    const result = await execution;

    expect(result).toMatchObject({ exitCode: 0, stderr: "" });
    expect(result.stdout).toContain(
      "Detected project files - Mise Environment pre-selected",
    );
    expect(result.stdout).toContain("Copied .mise.toml to build context");
    expect(app.workspace.readProjectFile(".sandbox/docker/.mise.toml")).toBe(
      "[tools]\nnode = 'lts'\n",
    );
  });

  test("reviews a generated Dockerfile only after customization is accepted", async () => {
    await using app = await setupSandboxAppTest();
    app.project.writeDockerfile("FROM custom-image\n");

    const execution = app.cli.run("init", "--project");
    await reviewProjectCapabilities(app);
    await openDiffActions(app, "docker/Dockerfile");
    await app.tui.user.enter();

    expect(await execution).toMatchObject({ exitCode: 0, stderr: "" });
    expect(
      app.workspace.readProjectFile(".sandbox/docker/Dockerfile"),
    ).toContain("Generated by: sandbox init");
  });

  test("accepts and rejects overwriting an existing project file", async () => {
    await using accepted = await setupSandboxAppTest();
    expect(
      (await accepted.cli.run("init", "--project", "--tools", "node")).exitCode,
    ).toBe(0);
    accepted.project.writeConfig("custom = 'accepted'\n");
    resetNonGitProject(accepted);
    const acceptExecution = accepted.cli.run("init", "--project");
    await accepted.tui.waitForText("Customize the project image?");
    await accepted.tui.user.enter();
    await openDiffActions(accepted, "config.toml");
    await accepted.tui.user.enter();
    expect((await acceptExecution).exitCode).toBe(0);
    expect(
      accepted.workspace.readProjectFile(".sandbox/config.toml"),
    ).not.toContain("custom = 'accepted'");

    await using rejected = await setupSandboxAppTest();
    expect(
      (await rejected.cli.run("init", "--project", "--tools", "node")).exitCode,
    ).toBe(0);
    rejected.project.writeConfig("custom = 'rejected'\n");
    resetNonGitProject(rejected);
    const rejectExecution = rejected.cli.run("init", "--project");
    await rejected.tui.waitForText("Customize the project image?");
    await rejected.tui.user.enter();
    await openDiffActions(rejected, "config.toml");
    await rejected.tui.user.down();
    await rejected.tui.user.enter();
    expect((await rejectExecution).exitCode).toBe(0);
    expect(rejected.workspace.readProjectFile(".sandbox/config.toml")).toBe(
      "custom = 'rejected'\n",
    );
  });

  test("cancels overwrite without changing existing files", async () => {
    await using app = await setupSandboxAppTest();
    expect(
      (await app.cli.run("init", "--project", "--tools", "node")).exitCode,
    ).toBe(0);
    app.project.writeConfig("custom = 'cancelled'\n");
    resetNonGitProject(app);

    const execution = app.cli.run("init", "--project");
    await app.tui.waitForText("Customize the project image?");
    await app.tui.user.enter();
    await openDiffActions(app, "config.toml");
    await app.tui.user.chord("c", { ctrl: true });
    const result = await execution;

    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("Cancelled.");
    expect(app.workspace.readProjectFile(".sandbox/config.toml")).toBe(
      "custom = 'cancelled'\n",
    );
  });

  test("preserves editor failure exit codes", async () => {
    await using app = await setupSandboxAppTest();
    expect(
      (await app.cli.run("init", "--project", "--tools", "node")).exitCode,
    ).toBe(0);
    app.project.writeConfig("custom = 'editor'\n");
    resetNonGitProject(app);
    app.editor.givenAvailableEditors(["code"]);

    const execution = app.cli.run("init", "--project");
    await app.tui.waitForText("Customize the project image?");
    await app.tui.user.enter();
    await openDiffActions(app, "config.toml");
    await app.tui.waitForText("Open diff in VS Code");
    app.processes.expectStart({ match: { command: "code" } }).resolveResult({
      exitCode: 42,
      stdout: "",
      stderr: "editor crashed",
    });
    await app.tui.user.enter();
    const result = await execution;

    expect(result.exitCode).toBe(42);
    expect(result.stderr).toContain("Editor code exited with code 42");
    expect(app.workspace.readProjectFile(".sandbox/config.toml")).toBe(
      "custom = 'editor'\n",
    );
  });

  test("reports filesystem failures without creating the remaining project files", async () => {
    await using app = await setupSandboxAppTest();
    app.project.makeConfigWriteFail();

    const result = await app.cli.run("init", "--project", "--tools", "node");

    expect(result.exitCode).toBe(1);
    expect(result.stderr).toContain("Failed to write");
    expect(app.workspace.projectFileExists(".sandbox/docker/Dockerfile")).toBe(
      false,
    );
  });

  test("is idempotent when explicit project initialization is rerun", async () => {
    await using app = await setupSandboxAppTest();
    const first = await app.cli.run("init", "--project", "--tools", "node");
    const config = app.workspace.readProjectFile(".sandbox/config.toml");
    const dockerfile = app.workspace.readProjectFile(
      ".sandbox/docker/Dockerfile",
    );
    resetNonGitProject(app);

    const second = await app.cli.run("init", "--project", "--tools", "node");

    expect(first.exitCode).toBe(0);
    expect(second.exitCode).toBe(0);
    expect(app.workspace.readProjectFile(".sandbox/config.toml")).toBe(config);
    expect(app.workspace.readProjectFile(".sandbox/docker/Dockerfile")).toBe(
      dockerfile,
    );
  });

  test("keeps parallel init roots, Git, settings, editor, and files isolated", async () => {
    await using first = await setupSandboxAppTest();
    await using second = await setupSandboxAppTest();

    const [firstResult, secondResult] = await Promise.all([
      first.cli.run("init", "--project", "--tools", "node"),
      second.cli.run("init", "--project", "--tools", "php"),
    ]);

    expect(firstResult.exitCode).toBe(0);
    expect(secondResult.exitCode).toBe(0);
    expect(first.workspace.root).not.toBe(second.workspace.root);
    expect(
      first.workspace.readProjectFile(".sandbox/docker/Dockerfile"),
    ).toContain("# Tools: node");
    expect(
      second.workspace.readProjectFile(".sandbox/docker/Dockerfile"),
    ).toContain("# Tools: php");
    expect(first.workspace.git.operations()).not.toBe(
      second.workspace.git.operations(),
    );
    expect(first.editor.launchedPaths()).toEqual([]);
    expect(second.editor.launchedPaths()).toEqual([]);
    expect(
      first.workspace.configFileExists("settings/.claude/settings.json"),
    ).toBe(false);
    expect(
      second.workspace.configFileExists("settings/.claude/settings.json"),
    ).toBe(false);
  });
});
